apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: projet-auto-decouvert
  description: Je suis apparu tout seul comme un grand !
spec:
  type: service
  lifecycle: experimental
  owner: user:ballakeita
